import type { Capability, CapabilityBundle, AuthRequirement } from '@specrail/core';

export interface SkillsExportOptions {
  includesDenied?: boolean;
}

// Export a capability bundle as a SKILLS.md markdown file.
//
// SKILLS files are human/agent-readable capability manifests.
// They describe what an API can do, how it's classified, what's allowed,
// and what auth is needed. This is the format that non-MCP agents and
// human reviewers consume.
//
// Design: Every capability appears in the output. Denied capabilities are
// clearly marked so agents understand what exists but is restricted.
export function exportSkills(bundle: CapabilityBundle, options: SkillsExportOptions = {}): string {
  const lines: string[] = [];
  const { source, capabilities, policy } = bundle;

  // Header
  lines.push(`# SKILLS: ${source.title} v${source.version}`);
  lines.push('');
  lines.push(`> Generated by Specrail. Source: ${source.specUrl}`);
  lines.push(
    `> Policy: ${policy.overlayName} | Allowed: ${policy.allowedCount}/${policy.totalCapabilities} | Denied: ${policy.deniedCount}/${policy.totalCapabilities}`,
  );
  lines.push('');

  // Group by classification
  const grouped = groupByClassification(capabilities);

  for (const [classification, caps] of Object.entries(grouped)) {
    const filteredCaps =
      options.includesDenied === false ? caps.filter((c) => c.policy.allowed) : caps;

    if (filteredCaps.length === 0) continue;

    lines.push(`## ${classification.charAt(0).toUpperCase() + classification.slice(1)} Operations`);
    lines.push('');

    for (const cap of filteredCaps) {
      lines.push(renderCapability(cap));
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push(
    `*Generated at ${bundle.generatedAt} | Bundle hash: ${bundle.bundleHash.slice(0, 12)}*`,
  );

  return lines.join('\n');
}

function renderCapability(cap: Capability): string {
  const lines: string[] = [];

  // Title with classification and policy status
  const status = cap.policy.allowed ? '' : ' [DENIED BY POLICY]';
  lines.push(`### ${cap.name} (${cap.classification})${status}`);

  // Description
  lines.push(cap.description || '*No description available.*');

  // Operation details
  lines.push(`- **Method:** ${cap.operation.method.toUpperCase()} ${cap.operation.path}`);

  // Parameters
  if (cap.operation.parameters.length > 0) {
    const paramList = cap.operation.parameters
      .map((p) => {
        const req = p.required ? 'required' : 'optional';
        const type =
          p.schema && typeof p.schema === 'object' && 'type' in p.schema
            ? String(p.schema.type)
            : 'string';
        return `${p.name} (${type}, ${req})`;
      })
      .join(', ');
    lines.push(`- **Parameters:** ${paramList}`);
  }

  // Auth
  if (cap.auth.length > 0) {
    lines.push(`- **Auth:** ${cap.auth.map(formatAuth).join(', ')}`);
  }

  // Policy status details for denied operations
  if (!cap.policy.allowed && cap.policy.denyReason) {
    lines.push(`- **Status:** Denied -- ${cap.policy.denyReason}`);
  }

  if (cap.policy.requiresApproval) {
    lines.push(`- **Note:** Requires human approval before execution`);
  }

  return lines.join('\n');
}

function formatAuth(auth: AuthRequirement): string {
  switch (auth.type) {
    case 'api-key':
      return `API Key (${auth.location ?? 'header'}: ${auth.name ?? 'X-API-Key'})`;
    case 'bearer':
      return 'Bearer Token';
    case 'basic':
      return 'Basic Auth';
    case 'oauth2':
      return `OAuth2${auth.scopes?.length ? ` (scopes: ${auth.scopes.join(', ')})` : ''}`;
    default:
      return auth.type;
  }
}

function groupByClassification(capabilities: Capability[]): Record<string, Capability[]> {
  const groups: Record<string, Capability[]> = {};
  for (const cap of capabilities) {
    const key = cap.classification;
    if (!groups[key]) groups[key] = [];
    groups[key].push(cap);
  }
  return groups;
}
